export const DUMMY_INCREMENT='DUMMY_INCREMENT';
export const LOCALE_SWITCH='LOCALE_SWITCH';
export const SESSION_STATE_SWITCH='SESSION_STATE_SWITCH';
export const LOGOUT = 'LOGOUT';
export const SET_DUMMY_VALUE = 'SET_DUMMY_VALUE';
